[package]
name = "execution-hub"
version.workspace = true
edition.workspace = true

[dependencies]
soroban-sdk = { version = "21.0.0", features = ["alloc"] }
shared = { path = "../../shared" }

[lib]
crate-type = ["cdylib"]
